### ISSUE TITLE
Issue loading modules in computer nodes

### ISSUE THREAD

**Issue by MariaICL** [c3nl-neuraldynamics/c3nl_cluster#52]
Hi, since the cluster issues this morning, I do not seem to be able to load any modules in the computer nodes. Not sure if it is a problem with just my user, I found out when I tried to submit an ANTs registration. 

Any idea of why this is happening? Thank you!

```
[myanezl2@brodmann23d ~]$ qlogin
Lmod has detected the following error:  The following module(s) are
unknown: "fsl/5.0.10"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "fsl/5.0.10"



Lmod has detected the following error:  The following module(s) are
unknown: "ANTs"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "ANTs"




Inactive Modules:
  1) ANTs        3) anaconda     5) freesurfer     7) matlab
  2) LCmodel     4) camino       6) fsl/5.0.10     8) mricron

Lmod has detected the following error:  The following module(s) are
unknown: "camino"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "camino"



Lmod has detected the following error:  The following module(s) are
unknown: "matlab"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "matlab"



Lmod has detected the following error:  The following module(s) are
unknown: "anaconda"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "anaconda"



Lmod has detected the following error:  The following module(s) are
unknown: "mricron"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "mricron"



Lmod has detected the following error:  The following module(s) are
unknown: "freesurfer"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "freesurfer"



Lmod has detected the following error:  The following module(s) are
unknown: "LCmodel"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "LCmodel"

```
The only module that seems to work for me at the moment in the computer nodes is gnu, all of the others do not seem to exist.
```
[myanezl2@compute-2-3 ~]$ module spider

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
The following is a list of the modules currently available:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
  gnu: gnu/5.4.0
    GNU Compiler Family (C/C++/Fortran for x86_64) 

---------------------------------------------------------------------------------------------------------------------
```

**Comment by GusZimmerman** [comment]
Getting a similar issue- cant run commands such as eddy/eddy_openmp when using fslsub 

Additionally when using qlogin, and module load fsl/5.0.10, I get the same error:

Lmod has detected the following error:  The following module(s) are unknown:
"fsl/5.0.10"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "fsl/5.0.10"

**Comment by james-cole** [comment]
I have the same issue

**Comment by petehellyer** [comment]
compute nodes are resetting now, should be fixed shortly.

**Comment by james-cole** [comment]
Still having problems in the lab... How long should the reset take?
